services:
  - type: pserv
    name: mysql
    runtime: image
    image: 
      url: abdallahasker/tmsmysql:latest 
    envVars:
      - key: MYSQL_HOST
        value: mysql
      - key: MYSQL_ROOT_PASSWORD
        value: askarpass
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: askarpass

  - type: web
    name: nestjs
    runtime: image
    image: 
      url: abdallahasker/backend-nestjs:latest
    envVars:
      - key: MYSQL_HOST
        value: mysql
      - key: MYSQL_ROOT_PASSWORD
        value: askarpass
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: askarpass
    
  - type: web
    name: frontend
    runtime: image
    image:
      url: abdallahasker/backend-frontend:latest 

