services:
  - name: mysql
    type: docker
    image: tmsmysql:latest 
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: askarpass
      - key: MYSQL_DATABASE
        value: tmsdb
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: askarpass
    healthCheck:
      path: /
      port: 3306

  - name: nestjs
    type: docker
    image: abdallahasker/backend-nestjs:latest
    envVars:
      - key: MYSQL_HOST
        value: mysql
      - key: MYSQL_ROOT_PASSWORD
        value: askarpass
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: askarpass
  - name: frontend
    type: docker
    image: abdallahasker/backend-frontend:latest 
    healthCheck:
      path: /
      port: 8080
routes:
  - path: /
    service: frontend  
    checkPath: /
    healthCheckTimeout: 5000

  - path: /api/*
    service: nestjs

