services:
  - type: pserv
    name: mysql
    runtime: image
    image: 
      url: abdallahasker/tmsmysql:latest 
    envVarGroup: database-var
    healthCheck:
      path: /
      port: 3306

  - type: pserv
    name: nestjs
    runtime: image
    image: 
      url: abdallahasker/backend-nestjs:latest
    envVarGroup: database-var
    
  - type: web
    name: frontend
    runtime: image
    image:
      url: abdallahasker/backend-frontend:latest 
    healthCheck:
      path: /
      port: 8080

routes:
  - path: /
    service: frontend  
    checkPath: /
    healthCheckTimeout: 5000

  - path: /api/*
    service: nestjs

envVarGroups:
  - name : database-var
    envVars:
      - key: MYSQL_HOST
        value: mysql
      - key: MYSQL_ROOT_PASSWORD
        value: askarpass
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: askarpass
