services:
  nestjs:
    build: .
    container_name: nestjs-container
    env_file:
      - .env
    ports:
      - "3000:3000"
  frontend:
    build: ../frontend
    container_name: nextjs-container
    ports:
      - "8080:8080"
    depends_on:
      - nestjs
