services:
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'

  nestjs:
    build: .
    container_name: nestjs-container
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  frontend:
    build: ../frontend
    container_name: nextjs-container
    ports:
      - "8080:8080"
    depends_on:
      - nestjs
